// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtevrbjslifqflbuydvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0ZXZyYmpzbGlmcWZsYnV5ZHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTA2MzQsImV4cCI6MjA2NTU4NjYzNH0.1hoiOQYAGJ0CAoO9x2NIytsMGJOiyGw-mmKpTjBsCMQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);